version: '3.4'

services:
  frontend:
    build:
      context: .
      target: app
    volumes:
      - ./:/opt/beabee-frontend/
    env_file:
      - .env
    environment:
      NODE_ENV: development
    command: [ 'node', './node_modules/.bin/nuxt' ]
    init: true

  router:
    build:
      context: .
      target: router
    env_file:
      - .env
    ports:
      - ${PORT}:80

volumes:
  db_data:
