name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      stage:
        description: "Stage"
        required: true
        default: "dev"

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.setvars.outputs.stage }}
      tag: ${{ steps.setvars.outputs.tag }}
    steps:
      - id: setvars
        run: |
          if [[ "${{ github.event.inputs.stage }}" == "dev" || "${{ github.ref }}" != "refs/heads/master" ]]; then
            echo "::set-output name=stage::dev"
            echo "::set-output name=tag::dev"
          else
            echo "::set-output name=stage::live"
            echo "::set-output name=tag::latest"
          fi

  push:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          target: app
          build-args: |
            REVISION=${{ steps.short-sha.outputs.sha }}
          tags: ${{ secrets.DOCKER_ORGANISATION }}/frontend:${{ needs.init.outputs.tag }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          target: router
          build-args: |
            REVISION=${{ steps.short-sha.outputs.sha }}
          tags: ${{ secrets.DOCKER_ORGANISATION }}/frontend-router:${{ needs.init.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs: [init, push]
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - run: ssh ${{ secrets.DEPLOY_SERVER }} ${{ needs.init.outputs.stage }}
